services:
  remnawave-switch-squads:
    image: docker.io/byte7up/remnawave-switch-squads:latest
    container_name: remnawave-switch-squads
    restart: unless-stopped
    environment:
      - RW_API_URL=${RW_API_URL}
      - RW_API_TOKEN=${RW_API_TOKEN}
      - BACKUP_SQUAD_UUID=${BACKUP_SQUAD_UUID}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - PORT=${PORT}
      - DATA_PATH=/data/original_squads.json
    volumes:
      - remnawave-switch-squads-data:/data
    ports:
      - "${BIND_HOST:-127.0.0.1}:${HOST_PORT:-3002}:${PORT:-3000}"
    networks:
      - remnawave-network

volumes:
  remnawave-switch-squads-data:

networks:
  remnawave-network:
    external: true
